# Generated by Django 5.0.6 on 2024-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commander_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='total',
            field=models.CharField(default='500', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commander',
            name='adresse',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commander',
            name='items',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commander',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commander',
            name='pays',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commander',
            name='ville',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commander',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
    ]
